
/* File generated by gen_cfile.py. Should not be modified. */

#include "TestSlave.h"
#include "ObjectDictionary.h"
//#include "global.h"
//#include "MC_PositionVelocityTime.h"
//#include "active_control.h"


#define CAN_PORT1 CAN1
#define CAN_NUM1  1
#define CAN1_TIM TIM2

//#include "MC_Top.h"
//extern MC_Typedef 				gMC;
/**************************************************************************/
/* Declaration of the mapped variables                                    */
/**************************************************************************/
UNS32 SlaveMap1 = 0x0;		/* Mapped at index 0x2000, subindex 0x00 */
UNS32 SlaveMap2 = 0x0;		/* Mapped at index 0x2001, subindex 0x00 */
UNS8 SlaveMap3 = 0x0;		/* Mapped at index 0x2002, subindex 0x00 */
UNS8 SlaveMap4 = 0x0;		/* Mapped at index 0x2003, subindex 0x00 */
UNS8 SlaveMap5 = 0x0;		/* Mapped at index 0x2004, subindex 0x00 */
UNS8 SlaveMap6 = 0x0;		/* Mapped at index 0x2005, subindex 0x00 */
UNS8 SlaveMap7 = 0x0;		/* Mapped at index 0x2006, subindex 0x00 */
UNS8 SlaveMap8 = 0x0;		/* Mapped at index 0x2007, subindex 0x00 */
UNS8 SlaveMap9 = 0x0;		/* Mapped at index 0x2008, subindex 0x00 */
UNS8 SlaveMap10 = 0x0;		/* Mapped at index 0x2009, subindex 0x00 */
UNS16 SlaveMap11 = 0x0;		/* Mapped at index 0x200A, subindex 0x00 */
INTEGER16 SlaveMap12 = 0x0;		/* Mapped at index 0x200B, subindex 0x00 */
INTEGER16 SlaveMap13 = 0x4D2;		/* Mapped at index 0x200C, subindex 0x00 */


/**************************************************************************/
/* Declaration of the value range types                                   */
/**************************************************************************/

#define valueRange_EMC 0x9F /* Type for index 0x1003 subindex 0x00 (only set of value 0 is possible) */
UNS32 TestSlave_valueRangeTest (UNS8 typeValue, void * value)
{
  switch (typeValue) {
    case valueRange_EMC:
      if (*(UNS8*)value != (UNS8)0) return OD_VALUE_RANGE_EXCEEDED;
      break;
  }
  return 0;
}

/* 这个对象字典中的回调函数都是用这个函数名来初始化的，这么干实属无奈之举，因为用数组成员赋值的方式会提示你不是一个常量或不是一个编译时常量
这个问题待后面解决*/
UNS32 Call_Null(CO_Data* d, const OD_OI_typeDef * d12, UNS8 bSubindex)
{
	return 0;
}



// data definition , data will be initialized when compiling 
/**************************************************************************/
/* The node id                                                            */
/**************************************************************************/
/* node_id default value.*/
UNS16 TestSlave_bDeviceNodeId = 0x00;

/**************************************************************************/
/* Array of message processing information */

UNS16 TestSlave_iam_a_slave = 0;

TIMER_HANDLE TestSlave_heartBeatTimers[4]={TIMER_NONE,TIMER_NONE,TIMER_NONE,TIMER_NONE};

/*
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

                               OBJECT DICTIONARY

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
*/


// TestSlave_Index1000全局结构体数组在程序中没有显示引用赋值。
// 在初始化阶段，利用指针的移动将TestSlave_Index1000中的数据拷贝给gOD数据，实现函数为OD_OI_Reg和OI_Recursion_Add。
// TestSlave_Index1000结构体数组在内存中对齐排列，
// 由于结构体数组中的&TestSlave_obj1000与对象字典中的&TestSlave_obj1000与指向同一地址，因此可以利用指针移动来拷贝数据。
// 该变量与TestSlave_objdict[]一起设定了对象字典索引及子索引以及数据的格式，再使用setODentry来设置对象字典的内容。
// 后面的数据功能与TestSlave_Index1000相同，不再各自单独说明。

UNS32 TestSlave_obj1000 = 0x00020192;	/* Canopen 402 协议 */
OD_OI_TypeDef TestSlave_Index1000[] = 
{
	{"Device Type", 0x10000000, OD_OBJCODE_VAR, OD_DATATYPE_U32, OD_ACCESS_R, (void *)&TestSlave_obj1000, 0, NULL, "16位的设备协议或应用协议 + 16位的逻辑设备的附加功能信息" },
};

///////////////////////////////////////////////////////////////////////////

UNS8 TestSlave_obj1001 = 0x00;	/* 0 */
OD_OI_TypeDef TestSlave_Index1001[] = 
{
	{"Error Register", 0x10010000, OD_OBJCODE_VAR, OD_DATATYPE_U8, OD_ACCESS_R, (void *)&TestSlave_obj1001, 0, NULL, "Canopen设备内部错误信息记录" },
};

////////////////////////////////////////////////////////////////////////////

extern OD_OI_TypeDef  Error_Field[];
UNS8 TestSlave_highestSubIndex_obj1003 = 0x00; /* 初值为啥无所谓，emergencyInit的时候会把这赋值为0，即清零*/
UNS32 TestSlave_obj1003[] = 
                    {
                      0x0,	/* TestSlave_obj1003[0]  */
                      0x0,	/* TestSlave_obj1003[1]  */
                      0x0,	/* TestSlave_obj1003[2]  */
                      0x0,	/* TestSlave_obj1003[3]  */
                      0x0,	/* TestSlave_obj1003[4]  */
                      0x0,	/* TestSlave_obj1003[5]  */
					  0x0,	/* TestSlave_obj1003[6]  */
                      0x0	/* TestSlave_obj1003[7]  */
                    };
					 /* 对象子索引回调函数列表 */
ODCallback_t TestSlave_Index1003_callbacks[] = 
										 {
										   Call_Null,
										   Call_Null,
										   Call_Null,
										   Call_Null,
										   Call_Null,
										   Call_Null,
										   Call_Null,
										   Call_Null,
										   Call_Null
										 };
				
OD_OI_TypeDef TestSlave_Index1003[] = 
{
	{"Pre-defined Error Field", 0x100300FF, OD_OBJCODE_ARRAY, OD_DATATYPE_U32, OD_ACCESS_RW, (void *)&Error_Field, 9, NULL, "Canopen设备内部错误信息记录" },
};

OD_OI_TypeDef  Error_Field[]=
{
  {"Number of errors", 0x10030000, OD_OBJCODE_NULL, OD_DATATYPE_U8,  OD_ACCESS_RW, (void *)&TestSlave_highestSubIndex_obj1003, 9, NULL, "错误数" }	,
  {"Error Field_1",    0x10030001, OD_OBJCODE_NULL, OD_DATATYPE_U32, OD_ACCESS_R,  (void *)&TestSlave_obj1003[0], 0, NULL, "最新的错误储存在这里，旧错误依次向下移" },
  {"Error Field_2",    0x10030002, OD_OBJCODE_NULL, OD_DATATYPE_U32, OD_ACCESS_R,  (void *)&TestSlave_obj1003[1], 0, NULL, "第2新的错误" },
  {"Error Field_3",    0x10030003, OD_OBJCODE_NULL, OD_DATATYPE_U32, OD_ACCESS_R,  (void *)&TestSlave_obj1003[2], 0, NULL, "第3新的错误" },
  {"Error Field_4",    0x10030004, OD_OBJCODE_NULL, OD_DATATYPE_U32, OD_ACCESS_R,  (void *)&TestSlave_obj1003[3], 0, NULL, "第4新的错误" },
  {"Error Field_5",    0x10030005, OD_OBJCODE_NULL, OD_DATATYPE_U32, OD_ACCESS_R,  (void *)&TestSlave_obj1003[4], 0, NULL, "第5新的错误" },
  {"Error Field_6",    0x10030006, OD_OBJCODE_NULL, OD_DATATYPE_U32, OD_ACCESS_R,  (void *)&TestSlave_obj1003[5], 0, NULL, "第6新的错误" },
  {"Error Field_7",    0x10030007, OD_OBJCODE_NULL, OD_DATATYPE_U32, OD_ACCESS_R,  (void *)&TestSlave_obj1003[6], 0, NULL, "第7新的错误" },
  {"Error Field_8",    0x10030008, OD_OBJCODE_NULL, OD_DATATYPE_U32, OD_ACCESS_R,  (void *)&TestSlave_obj1003[7], 0, NULL, "第8新的错误" },
};

///////////////////////////////////////////////////////////////////////////

UNS32 TestSlave_obj1005 = 0x00000080;	/* 0 */
ODCallback_t TestSlave_Index1005_callbacks[] = 
 {
   NULL,
 };
OD_OI_TypeDef TestSlave_Index1005[] = 
{
	{"SYNC COB ID", 0x10050000, OD_OBJCODE_VAR, OD_DATATYPE_U32, OD_ACCESS_RW, (void *)&TestSlave_obj1005, 0, NULL, "已配置的同步对象的COB-ID" },
};

///////////////////////////////////////////////////////////////////////////

UNS32 TestSlave_obj1006 = 0x0;	/* 0 */
ODCallback_t TestSlave_Index1006_callbacks[] = 
 {
   NULL,
 };
OD_OI_TypeDef TestSlave_Index1006[] = 
{
	{"Communication Cycle Period", 0x10060000, OD_OBJCODE_VAR, OD_DATATYPE_U32, OD_ACCESS_RW, (void *)&TestSlave_obj1006, 0, NULL, "SYNC时间间隔，单位是us" },
};

///////////////////////////////////////////////////////////////////////////

UNS16 TestSlave_obj100C = 0x0;	/* 不推荐使用节点监护，所以此处设置为0 */
ODCallback_t TestSlave_Index100C_callbacks[] = 
 {
   NULL,
 };
OD_OI_TypeDef TestSlave_Index100C[] = 
{
	{"GuardTime", 0x100C0000, OD_OBJCODE_VAR, OD_DATATYPE_U16, OD_ACCESS_RW, (void *)&TestSlave_obj100C, 0, NULL, "监护周期，单位为ms" },
};

///////////////////////////////////////////////////////////////////////////

UNS8 TestSlave_obj100D = 0x0;	/* 不推荐使用节点监护，所以此处设置为0 */
ODCallback_t TestSlave_Index100D_callbacks[] = 
 {
   NULL,
 };
OD_OI_TypeDef TestSlave_Index100D[] = 
{
	{"LifeTimeFactor", 0x100D0000, OD_OBJCODE_VAR, OD_DATATYPE_U8, OD_ACCESS_RW, (void *)&TestSlave_obj100D, 0, NULL, "生存周期因子" },
};

///////////////////////////////////////////////////////////////////////////

extern OD_OI_TypeDef  Store_parameters[];
UNS8 TestSlave_highestSubIndex_obj1010 = 4; /* number of subindex - 1*/
UNS32 TestSlave_obj1010[] = 
                    {
                      0x0,	/* TestSlave_obj1010[0] */
                      0x0,	/* TestSlave_obj1010[1] */
                      0x0,	/* TestSlave_obj1010[2] */
                      0x0,	/* TestSlave_obj1010[3] */
                    };
ODCallback_t TestSlave_Index1010_callbacks[] = 
{
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
};
OD_OI_TypeDef TestSlave_Index1010[] = 
{
	{"Store parameters", 0x101000FF, OD_OBJCODE_ARRAY, OD_DATATYPE_U32, OD_ACCESS_RW, (void *)&Store_parameters, 6, NULL, "此对象控制保存参数到非易失性存储器中" },
};
OD_OI_TypeDef  Store_parameters[]=
{
  {"highest sub-index supported",   0x10100000, OD_OBJCODE_NULL, OD_DATATYPE_U8,  OD_ACCESS_C,  (void *)&TestSlave_highestSubIndex_obj1010, 0, NULL, "最高子索引数" },	
  {"Save_All_Parameters",           0x10100001, OD_OBJCODE_NULL, OD_DATATYPE_U32, OD_ACCESS_RW, (void *)&TestSlave_obj1010[0], 0, NULL, "保存所有参数" },
  {"Save_Communication_Parameters", 0x10100002, OD_OBJCODE_NULL, OD_DATATYPE_U32, OD_ACCESS_RW, (void *)&TestSlave_obj1010[1], 0, NULL, "保存通信参数" },
  {"Save_Application_Parameters",   0x10100003, OD_OBJCODE_NULL, OD_DATATYPE_U32, OD_ACCESS_RW, (void *)&TestSlave_obj1010[2], 0, NULL, "保存应用参数" },
  {"SaveDriverParameters",  0x10100004, OD_OBJCODE_NULL, OD_DATATYPE_U32, OD_ACCESS_RW, (void *)&TestSlave_obj1010[3], 0, NULL, "保存制造商定义的参数" },
  {"SaveJointBoardParameters",  0x10100005, OD_OBJCODE_NULL, OD_DATATYPE_U32, OD_ACCESS_RW, (void *)&TestSlave_obj1010[4], 0, NULL, "保存制造商定义的参数" },  
};

///////////////////////////////////////////////////////////////////////////

extern OD_OI_TypeDef  Restore_Default_Parameters[];
UNS8 TestSlave_highestSubIndex_obj1011 = 5; /* number of subindex - 1*/
UNS32 TestSlave_obj1011[] = 
                    {
                      0x0,	/* 0x10110001 */
                      0x0,	/* 0x10110002 */
                      0x0,	/* 0x10110003 */
                      0x0,	/* 0x10110004 */
                      0x0,	/* 0x10110005 */						
                    };
ODCallback_t TestSlave_Index1011_callbacks[] = 
 {
   NULL,
   NULL,
   NULL,
   NULL,
   NULL,
   NULL,
 };
OD_OI_TypeDef TestSlave_Index1011[] = 
{
	{"Restore Default Parameters", 0x101100FF, OD_OBJCODE_ARRAY, OD_DATATYPE_U32, OD_ACCESS_RW, (void *)&Restore_Default_Parameters, 6, NULL, "此对象控制保存参数到非易失性存储器中" },
};
OD_OI_TypeDef  Restore_Default_Parameters[]=
{
  {"highest sub-index supported",              0x10110000, OD_OBJCODE_NULL, OD_DATATYPE_U8,  OD_ACCESS_C,  (void *)&TestSlave_highestSubIndex_obj1011, 0, NULL, "最高子索引数" },	
  {"Restore_All_Default_Parameters",           0x10110001, OD_OBJCODE_NULL, OD_DATATYPE_U32, OD_ACCESS_RW, (void *)&TestSlave_obj1011[0], 0, NULL, "恢复所有的默认参数" },
  {"Restore_Communication_Default_Parameters", 0x10110002, OD_OBJCODE_NULL, OD_DATATYPE_U32, OD_ACCESS_RW, (void *)&TestSlave_obj1011[1], 0, NULL, "恢复通信的默认参数" },
  {"Restore_Application_Default_Parameters",   0x10110003, OD_OBJCODE_NULL, OD_DATATYPE_U32, OD_ACCESS_RW, (void *)&TestSlave_obj1011[2], 0, NULL, "恢复应用的默认参数" },
  {"RestoreDriverDefaultParameters",           0x10110004, OD_OBJCODE_NULL, OD_DATATYPE_U32, OD_ACCESS_RW, (void *)&TestSlave_obj1011[3], 0, NULL, "恢复制造商的默认参数" },
  {"RestoreJointBoardDefaultParameters",       0x10110005, OD_OBJCODE_NULL, OD_DATATYPE_U32, OD_ACCESS_RW, (void *)&TestSlave_obj1011[4], 0, NULL, "恢复制造商的默认参数" },  
};

///////////////////////////////////////////////////////////////////////////

UNS32 TestSlave_obj1014 = 0;	/* 0x80 + Node-ID */
OD_OI_TypeDef TestSlave_Index1014[] = 
{
	{"Emergency COB ID", 0x10140000, OD_OBJCODE_VAR, OD_DATATYPE_U32, OD_ACCESS_RW, (void *)&TestSlave_obj1014, 0, NULL, "应急消息 COB_ID" },
};

///////////////////////////////////////////////////////////////////////////

extern OD_OI_TypeDef  Consumer_Heartbeat_Time[];
UNS8 TestSlave_highestSubIndex_obj1016 = 4;
UNS32 TestSlave_obj1016[] = 
                    {
                      0x0,	/* 0x10160001 */
                      0x0,	/* 0x10160002 */
                      0x0,	/* 0x10160003 */
                      0x0,	/* 0x10160004 */
                    };
OD_OI_TypeDef TestSlave_Index1016[] = 
{
	{"Consumer Heartbeat Time", 0x101600FF, OD_OBJCODE_ARRAY, OD_DATATYPE_U32, OD_ACCESS_RW, (void *)&Consumer_Heartbeat_Time, 5, NULL, "消费者心跳超时" },
};
OD_OI_TypeDef  Consumer_Heartbeat_Time[]=
{
  {"number of HeartBeat Consumer", 0x10160000, OD_OBJCODE_NULL, OD_DATATYPE_U8,  OD_ACCESS_C,   (void *)&TestSlave_highestSubIndex_obj1016, 0, NULL, "心跳消费者数目,单位为ms" },	
  {"Consumer1_Heartbeat_Time",     0x10160001, OD_OBJCODE_NULL, OD_DATATYPE_U32, OD_ACCESS_RW,  (void *)&TestSlave_obj1016[0], 0, NULL, "消费者心跳1" },
  {"Consumer2_Heartbeat_Time",     0x10160002, OD_OBJCODE_NULL, OD_DATATYPE_U32, OD_ACCESS_RW,  (void *)&TestSlave_obj1016[1], 0, NULL, "消费者心跳2" },
  {"Consumer3_Heartbeat_Time",     0x10160003, OD_OBJCODE_NULL, OD_DATATYPE_U32, OD_ACCESS_RW,  (void *)&TestSlave_obj1016[2], 0, NULL, "消费者心跳3" },
  {"Consumer4_Heartbeat_Time",     0x10160004, OD_OBJCODE_NULL, OD_DATATYPE_U32, OD_ACCESS_RW,  (void *)&TestSlave_obj1016[3], 0, NULL, "消费者心跳4" },
};

///////////////////////////////////////////////////////////////////////////

UNS16 TestSlave_obj1017 = 0;	/* 0 */
ODCallback_t TestSlave_Index1017_callbacks[] = 
 {
   NULL,
 };
OD_OI_TypeDef TestSlave_Index1017[] = 
{
	{"Producer Heartbeat Time", 0x10170000, OD_OBJCODE_VAR, OD_DATATYPE_U16, OD_ACCESS_RW, (void *)&TestSlave_obj1017, 0, NULL, "生产者心跳超时" },
};

///////////////////////////////////////////////////////////////////////////

extern OD_OI_TypeDef  Identity[];
UNS8 TestSlave_highestSubIndex_obj1018 = 4; /* number of subindex - 1*/
UNS32 TestSlave_obj1018[] = 
                    {
                      0x0,	/* 0x10180000 */
                      0x0,	/* 0x10180001 */
                      0x0,	/* 0x10180002 */
                      0x0,	/* 0x10180003 */
                    };
OD_OI_TypeDef TestSlave_Index1018[] = 
{
	{"Identity", 0x101800FF, OD_OBJCODE_RECORD, OD_DATATYPE_ID, OD_ACCESS_R, (void *)&Identity, 5, NULL, "消费者心跳超时" },
};
OD_OI_TypeDef  Identity[]=
{
  {"highest subindex supported", 0x10180000, OD_OBJCODE_NULL, OD_DATATYPE_U8,  OD_ACCESS_C,  (void *)&TestSlave_highestSubIndex_obj1018, 0, NULL, "最高子索引数" },	
  {"Vendor_ID",                  0x10180001, OD_OBJCODE_NULL, OD_DATATYPE_U32, OD_ACCESS_R,  (void *)&TestSlave_obj1018[0], 0, NULL, "Vendor_ID" },
  {"Product_Code",     			 0x10180002, OD_OBJCODE_NULL, OD_DATATYPE_U32, OD_ACCESS_R,  (void *)&TestSlave_obj1018[1], 0, NULL, "产品码" },
  {"Revision_Number",     	     0x10180003, OD_OBJCODE_NULL, OD_DATATYPE_U32, OD_ACCESS_R,  (void *)&TestSlave_obj1018[2], 0, NULL, "修订版本号" },
  {"Serial_Number",    			 0x10180004, OD_OBJCODE_NULL, OD_DATATYPE_U32, OD_ACCESS_R,  (void *)&TestSlave_obj1018[3], 0, NULL, "序列号" },
};

///////////////////////////////////////////////////////////////////////////

extern OD_OI_TypeDef  Server_SDO_Parameter[];
UNS8 TestSlave_highestSubIndex_obj1200 = 3; /* number of subindex - 1*/
UNS32 TestSlave_obj1200[] = 
                    {
                      0x600,	/* 600h + Node-ID */
                      0x580,	/* 580h + Node-ID */
                      0x000,
                    };
OD_OI_TypeDef TestSlave_Index1200[] = 
{
	{"SSDO Par", 0x120000FF, OD_OBJCODE_RECORD, OD_DATATYPE_SDOP, OD_ACCESS_R, (void *)&Server_SDO_Parameter, 4, NULL, "SDO服务器参数" },
};
OD_OI_TypeDef  Server_SDO_Parameter[]=
{
  {"highest subindex supported",           0x12000000, OD_OBJCODE_NULL, OD_DATATYPE_U8,  OD_ACCESS_C,  (void *)&TestSlave_highestSubIndex_obj1200, 0, NULL, "最高子索引数" },	
  {"COB_ID_Client_to_Server_Receive_SDO",  0x12000001, OD_OBJCODE_NULL, OD_DATATYPE_U32, OD_ACCESS_RW,  (void *)&TestSlave_obj1200[0], 0, NULL, "客户端 -> 服务器 COB_ID" },
  {"COB_ID_Server_to_Client_Transmit_SDO", 0x12000002, OD_OBJCODE_NULL, OD_DATATYPE_U32, OD_ACCESS_RW,  (void *)&TestSlave_obj1200[1], 0, NULL, "服务器 -> 客户端 COB_ID" },
  {"Node-ID of the SDO client",            0x12000003, OD_OBJCODE_NULL, OD_DATATYPE_U8,  OD_ACCESS_RW,  (void *)&TestSlave_obj1200[2], 0, NULL, "客户端 COB_ID" },
};

///////////////////////////////////////////////////////////////////////////

extern OD_OI_TypeDef  Client_SDO_Parameter[];
UNS8 TestSlave_highestSubIndex_obj1280 = 3; /* number of subindex - 1*/
UNS32 TestSlave_obj1280[] = 
                    {
                      0x580,	/* 600h + Node-ID */
                      0x600,	/* 600h + Node-ID */
					  0,
                    };
OD_OI_TypeDef TestSlave_Index1280[] = 
{
	{"CSDO Par", 0x128000FF, OD_OBJCODE_RECORD, OD_DATATYPE_SDOP, OD_ACCESS_R, (void *)&Client_SDO_Parameter, 4, NULL, "SDO服务器参数" },
};
OD_OI_TypeDef  Client_SDO_Parameter[]=
{
  {"highest subindex supported",            0x12800000, OD_OBJCODE_NULL, OD_DATATYPE_U8,  OD_ACCESS_C,   (void *)&TestSlave_highestSubIndex_obj1280, 0, NULL, "最高子索引数" },	
  {"COB_ID_Client_to_Server_Transmit_SDO",  0x12800001, OD_OBJCODE_NULL, OD_DATATYPE_U32, OD_ACCESS_RW,  (void *)&TestSlave_obj1280[0], 0, NULL, "客户端 -> 服务器 COB_ID" },
  {"COB_ID_Server_to_Client_Receive_SDO",   0x12800002, OD_OBJCODE_NULL, OD_DATATYPE_U32, OD_ACCESS_RW,  (void *)&TestSlave_obj1280[1], 0, NULL, "服务器 -> 客户端 COB_ID" },
  {"Node-ID of the SDO server",             0x12800003, OD_OBJCODE_NULL, OD_DATATYPE_U8,  OD_ACCESS_RW,  (void *)&TestSlave_obj1280[2], 0, NULL, "服务器COB_ID" },
};

///////////////////////////////////////////////////////////////////////////
/**************************************************************************************************************************************/
/**************************************************************************************************************************************/
extern OD_OI_TypeDef  Receive_PDO_1_Parameter[];
UNS8 TestSlave_highestSubIndex_obj1400 = 5; /* number of subindex - 1*/
UNS32 TestSlave_obj1400[] = 
                    {
                      0x200,	/* 0x18000001 */
                      0,	/* 0x18000002 */
					  0,	/* 0x18000003 */
                      0,	/* 0x18000004 */
                      0,	/* 0x18000005 */
                    };
ODCallback_t TestSlave_Index1400_callbacks[] = 
 {
   NULL,
   NULL,
   NULL,
   NULL,
   NULL,
   NULL,
 };
OD_OI_TypeDef TestSlave_Index1400[] = 
{
	{"RPDO1 Com", 0x140000FF, OD_OBJCODE_RECORD, OD_DATATYPE_PDOCP, OD_ACCESS_RW, (void *)&Receive_PDO_1_Parameter, 6, NULL, "SDO服务器参数" },
};
OD_OI_TypeDef  Receive_PDO_1_Parameter[]=
{
  {"RPDO1 SubCount", 0x14000000, OD_OBJCODE_NULL, OD_DATATYPE_U8,  OD_ACCESS_C,   (void *)&TestSlave_highestSubIndex_obj1400, 0, NULL, "最高子索引数" },	
  {"RPDO1 COB_ID_used_by_PDO",  		   0x14000001, OD_OBJCODE_NULL, OD_DATATYPE_U32, OD_ACCESS_RW,  (void *)&TestSlave_obj1400[0], 0, NULL, "TPDO使用的COB_ID" },
  {"RPDO1 Transmission_Type", 		     0x14000002, OD_OBJCODE_NULL, OD_DATATYPE_U8,  OD_ACCESS_RW,  (void *)&TestSlave_obj1400[1], 0, NULL, "传输类型" },
  {"RPDO1 Inhibit_Time",  			       0x14000003, OD_OBJCODE_NULL, OD_DATATYPE_U32, OD_ACCESS_RW,  (void *)&TestSlave_obj1400[2], 0, NULL, "抑制时间，单位为100us" },
  {"RPDO1 Compatibility_Entry",		     0x14000004, OD_OBJCODE_NULL, OD_DATATYPE_U8,  OD_ACCESS_RW,  (void *)&TestSlave_obj1400[3], 0, NULL, "保留" },
  {"RPDO1 Event_Timer", 				       0x14000005, OD_OBJCODE_NULL, OD_DATATYPE_U32, OD_ACCESS_RW,  (void *)&TestSlave_obj1400[4], 0, NULL, "事件定时器,单位为ms" }
};

///////////////////////////////////////////////////////////////////////////

extern OD_OI_TypeDef  Receive_PDO_2_Parameter[];
UNS8 TestSlave_highestSubIndex_obj1401 = 5; /* number of subindex - 1*/
UNS32 TestSlave_obj1401[] = 
                    {
                      0x300,	/* 0x18010001 */
                      0x0,	/* 0x18010002 */
					            0x0,	/* 0x18010003 */
                      0x0,	/* 0x18010004 */
                      0x0,	/* 0x18010005 */
                    };
ODCallback_t TestSlave_Index1401_callbacks[] = 
 {
   NULL,
   NULL,
   NULL,
   NULL,
   NULL,
   NULL,
 };
OD_OI_TypeDef TestSlave_Index1401[] = 
{
	{"RPDO2 Com", 0x140100FF, OD_OBJCODE_RECORD, OD_DATATYPE_PDOCP, OD_ACCESS_RW, (void *)&Receive_PDO_2_Parameter, 6, NULL, "SDO服务器参数" },
};
OD_OI_TypeDef  Receive_PDO_2_Parameter[]=
{
  {"RPDO2 SubCount", 0x14010000, OD_OBJCODE_NULL, OD_DATATYPE_U8,  OD_ACCESS_C,   (void *)&TestSlave_highestSubIndex_obj1401, 0, NULL, "最高子索引数" },	
  {"RPDO2 COB_ID_used_by_PDO",  	     0x14010001, OD_OBJCODE_NULL, OD_DATATYPE_U32, OD_ACCESS_RW,  (void *)&TestSlave_obj1401[0], 0, NULL, "TPDO使用的COB_ID" },
  {"RPDO2 Transmission_Type", 		     0x14010002, OD_OBJCODE_NULL, OD_DATATYPE_U8,  OD_ACCESS_RW,  (void *)&TestSlave_obj1401[1], 0, NULL, "传输类型" },
  {"RPDO2 Inhibit_Time",  			       0x14010003, OD_OBJCODE_NULL, OD_DATATYPE_U32, OD_ACCESS_RW,  (void *)&TestSlave_obj1401[2], 0, NULL, "抑制时间，单位为100us" },
  {"RPDO2 Compatibility_Entry",		     0x14010004, OD_OBJCODE_NULL, OD_DATATYPE_U8,  OD_ACCESS_RW,  (void *)&TestSlave_obj1401[3], 0, NULL, "保留" },
  {"RPDO2 Event_Timer", 				       0x14010005, OD_OBJCODE_NULL, OD_DATATYPE_U32, OD_ACCESS_RW,  (void *)&TestSlave_obj1401[4], 0, NULL, "事件定时器,单位为ms" },
};

///////////////////////////////////////////////////////////////////////////

extern OD_OI_TypeDef  Receive_PDO_3_Parameter[];
UNS8 TestSlave_highestSubIndex_obj1402 = 5; /* number of subindex - 1*/
UNS32 TestSlave_obj1402[] = 
                    {
                      0x400,	/* 0x18020001 */
                      0x0,	/* 0x18020002 */
					            0x0,	/* 0x18020003 */
                      0x0,	/* 0x18020004 */
                      0x0,	/* 0x18020005 */
                    };
ODCallback_t TestSlave_Index1402_callbacks[] = 
 {
   NULL,
   NULL,
   NULL,
   NULL,
   NULL,
   NULL,
 };
OD_OI_TypeDef TestSlave_Index1402[] = 
{
	{"RPDO3 Com", 0x140200FF, OD_OBJCODE_RECORD, OD_DATATYPE_PDOCP, OD_ACCESS_RW, (void *)&Receive_PDO_3_Parameter, 6, NULL, "SDO服务器参数" },
};
OD_OI_TypeDef  Receive_PDO_3_Parameter[]=
{
  {"RPDO3 SubCount", 0x14020000, OD_OBJCODE_NULL, OD_DATATYPE_U8,  OD_ACCESS_C,   (void *)&TestSlave_highestSubIndex_obj1402, 0, NULL, "最高子索引数" },	
  {"RPDO3 COB_ID_used_by_PDO",  		   0x14020001, OD_OBJCODE_NULL, OD_DATATYPE_U32, OD_ACCESS_RW,  (void *)&TestSlave_obj1402[0], 0, NULL, "TPDO使用的COB_ID" },
  {"RPDO3 Transmission_Type", 		     0x14020002, OD_OBJCODE_NULL, OD_DATATYPE_U8,  OD_ACCESS_RW,  (void *)&TestSlave_obj1402[1], 0, NULL, "传输类型" },
  {"RPDO3 Inhibit_Time",  			       0x14020003, OD_OBJCODE_NULL, OD_DATATYPE_U32, OD_ACCESS_RW,  (void *)&TestSlave_obj1402[2], 0, NULL, "抑制时间，单位为100us" },
  {"RPDO3 Compatibility_Entry",		     0x14020004, OD_OBJCODE_NULL, OD_DATATYPE_U8,  OD_ACCESS_RW,  (void *)&TestSlave_obj1402[3], 0, NULL, "保留" },
  {"RPDO3 Event_Timer", 				       0x14020005, OD_OBJCODE_NULL, OD_DATATYPE_U32, OD_ACCESS_RW,  (void *)&TestSlave_obj1402[4], 0, NULL, "事件定时器,单位为ms" },
};

///////////////////////////////////////////////////////////////////////////

extern OD_OI_TypeDef  Receive_PDO_4_Parameter[];
UNS8 TestSlave_highestSubIndex_obj1403 = 5; /* number of subindex - 1*/
UNS32 TestSlave_obj1403[] = 
                    {
                      0x500,	/* 0x18030001 */
                      0x0,	/* 0x18030002 */
					            0x0,	/* 0x18030003 */
                      0x0,	/* 0x18030004 */
                      0x0,	/* 0x18030005 */
                    };
					ODCallback_t TestSlave_Index1403_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
OD_OI_TypeDef TestSlave_Index1403[] = 
{
	{"RPDO4 Com", 0x140300FF, OD_OBJCODE_RECORD, OD_DATATYPE_PDOCP, OD_ACCESS_RW, (void *)&Receive_PDO_4_Parameter, 6, NULL, "SDO服务器参数" },
};
OD_OI_TypeDef  Receive_PDO_4_Parameter[]=
{
  {"RPDO4 SubCount", 0x14030000, OD_OBJCODE_NULL, OD_DATATYPE_U8,  OD_ACCESS_C,   (void *)&TestSlave_highestSubIndex_obj1403, 0, NULL, "最高子索引数" },	
  {"RPDO4 COB_ID_used_by_PDO",  		   0x14030001, OD_OBJCODE_NULL, OD_DATATYPE_U32, OD_ACCESS_RW,  (void *)&TestSlave_obj1403[0], 0, NULL, "TPDO使用的COB_ID" },
  {"RPDO4 Transmission_Type", 		     0x14030002, OD_OBJCODE_NULL, OD_DATATYPE_U8,  OD_ACCESS_RW,  (void *)&TestSlave_obj1403[1], 0, NULL, "传输类型" },
  {"RPDO4 Inhibit_Time",  			       0x14030003, OD_OBJCODE_NULL, OD_DATATYPE_U32, OD_ACCESS_RW,  (void *)&TestSlave_obj1403[2], 0, NULL, "抑制时间，单位为100us" },
  {"RPDO4 Compatibility_Entry",		     0x14030004, OD_OBJCODE_NULL, OD_DATATYPE_U8,  OD_ACCESS_RW,  (void *)&TestSlave_obj1403[3], 0, NULL, "保留" },
  {"RPDO4 Event_Timer", 				       0x14030005, OD_OBJCODE_NULL, OD_DATATYPE_U32, OD_ACCESS_RW,  (void *)&TestSlave_obj1403[4], 0, NULL, "事件定时器,单位为ms" },
};

///////////////////////////////////////////////////////////////////////////

extern OD_OI_TypeDef  Receive_PDO_5_Parameter[];
UNS8 TestSlave_highestSubIndex_obj1404 = 5; /* number of subindex - 1*/
UNS32 TestSlave_obj1404[] = 
                    {
                      0x501,	/* 0x18040001 */
                      0xFD,	/* 0x18040002 */
					            0x0,	/* 0x18040003 */
                      0x0,	/* 0x18040004 */
                      0x0,	/* 0x18040005 */
                    };
				     ODCallback_t TestSlave_Index1404_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
OD_OI_TypeDef TestSlave_Index1404[] = 
{
	{"RPDO5 Com", 0x140400FF, OD_OBJCODE_RECORD, OD_DATATYPE_PDOCP, OD_ACCESS_RW, (void *)&Receive_PDO_5_Parameter, 6, NULL, "SDO服务器参数" },
};
OD_OI_TypeDef  Receive_PDO_5_Parameter[]=
{
  {"RPDO5 SubCount", 0x14040000, OD_OBJCODE_NULL, OD_DATATYPE_U8,  OD_ACCESS_C,   (void *)&TestSlave_highestSubIndex_obj1404, 0, NULL, "最高子索引数" },	
  {"RPDO5 COB_ID_used_by_PDO",  		   0x14040001, OD_OBJCODE_NULL, OD_DATATYPE_U32, OD_ACCESS_RW,  (void *)&TestSlave_obj1404[0], 0, NULL, "TPDO使用的COB_ID" },
  {"RPDO5 Transmission_Type", 		     0x14040002, OD_OBJCODE_NULL, OD_DATATYPE_U8,  OD_ACCESS_RW,  (void *)&TestSlave_obj1404[1], 0, NULL, "传输类型" },
  {"RPDO5 Inhibit_Time",  			       0x14040003, OD_OBJCODE_NULL, OD_DATATYPE_U32, OD_ACCESS_RW,  (void *)&TestSlave_obj1404[2], 0, NULL, "抑制时间，单位为100us" },
  {"RPDO5 Compatibility_Entry",		     0x14040004, OD_OBJCODE_NULL, OD_DATATYPE_U8,  OD_ACCESS_RW,  (void *)&TestSlave_obj1404[3], 0, NULL, "保留" },
  {"RPDO5 Event_Timer", 				       0x14040005, OD_OBJCODE_NULL, OD_DATATYPE_U32, OD_ACCESS_RW,  (void *)&TestSlave_obj1404[4], 0, NULL, "事件定时器,单位为ms" },
};

///////////////////////////////////////////////////////////////////////////

extern OD_OI_TypeDef  Receive_PDO_1_Mapping[];
UNS8 TestSlave_highestSubIndex_obj1600 = 4; /* number of subindex - 1*/
UNS32 TestSlave_obj1600[] =
                    {
                      0,	/* 536870913 */
                      0,	/* 536936449 */
                      0,	/* 537001985 */
                      0,	/* 537067521 */
//                      0,	/* 537133057 */
//                      0,	/* 537198593 */
//                      0,	/* 537264129 */
//                      0,	/* 537329665 */
//                      0,	/* 537395208 */
//                      0	/* 537460768 */
                    };
OD_OI_TypeDef TestSlave_Index1600[] = 
{
	{"RPDO1 Mapping", 0x160000FF, OD_OBJCODE_RECORD, OD_DATATYPE_PDOMAP, OD_ACCESS_RW, (void *)&Receive_PDO_1_Mapping, 5, NULL, "RPDO1映射参数" },
};
OD_OI_TypeDef  Receive_PDO_1_Mapping[]=
{
  {"RPDO1 MappingCount", 0x16000000, OD_OBJCODE_NULL, OD_DATATYPE_U8,  OD_ACCESS_RW,  (void *)&TestSlave_highestSubIndex_obj1600, 0, NULL, "最高子索引数" },	
  {"RPDO1 Mapping1",  	    0x16000001, OD_OBJCODE_NULL, OD_DATATYPE_U32, OD_ACCESS_RW,  (void *)&TestSlave_obj1600[0], 0, NULL, "映射参数值为20000001" },
  {"RPDO1 Mapping2", 	    0x16000002, OD_OBJCODE_NULL, OD_DATATYPE_U32, OD_ACCESS_RW,  (void *)&TestSlave_obj1600[1], 0, NULL, "映射参数值为20010001" },
  {"RPDO1 Mapping3",  	    0x16000003, OD_OBJCODE_NULL, OD_DATATYPE_U32, OD_ACCESS_RW,  (void *)&TestSlave_obj1600[2], 0, NULL, "映射参数值为20020001" },
  {"RPDO1 Mapping4",		0x16000004, OD_OBJCODE_NULL, OD_DATATYPE_U32, OD_ACCESS_RW,  (void *)&TestSlave_obj1600[3], 0, NULL, "映射参数值为20030001" },
//  {"RPDO1 Mapping5", 	    0x16000005, OD_OBJCODE_NULL, OD_DATATYPE_U32, OD_ACCESS_RW,  (void *)&TestSlave_obj1600[4], 0, NULL, "映射参数值为20040001" },
//  {"RPDO1 Mapping6",  	    0x16000006, OD_OBJCODE_NULL, OD_DATATYPE_U32, OD_ACCESS_RW,  (void *)&TestSlave_obj1600[5], 0, NULL, "映射参数值为20050001" },
//  {"RPDO1 Mapping7", 	    0x16000007, OD_OBJCODE_NULL, OD_DATATYPE_U32, OD_ACCESS_RW,  (void *)&TestSlave_obj1600[6], 0, NULL, "映射参数值为20060001" },
//  {"RPDO1 Mapping8",  	    0x16000008, OD_OBJCODE_NULL, OD_DATATYPE_U32, OD_ACCESS_RW,  (void *)&TestSlave_obj1600[7], 0, NULL, "映射参数值为20070001" },
//  {"RPDO1 Mapping9",		    0x16000009, OD_OBJCODE_NULL, OD_DATATYPE_U32, OD_ACCESS_RW,  (void *)&TestSlave_obj1600[8], 0, NULL, "映射参数值为20080008" },
//  {"RPDO1 MappingA", 	    0x1600000A, OD_OBJCODE_NULL, OD_DATATYPE_U32, OD_ACCESS_RW,  (void *)&TestSlave_obj1600[9], 0, NULL, "映射参数值为20090020" },
};

///////////////////////////////////////////////////////////////////////////

extern OD_OI_TypeDef  Receive_PDO_2_Mapping[];
UNS8 TestSlave_highestSubIndex_obj1601 = 8; /* number of subindex - 1*/
UNS32 TestSlave_obj1601[] = 
                    {
						0,	
						0,	
						0,	
						0,	
						0,	
						0,	
						0,	
						0,	
                    };
OD_OI_TypeDef TestSlave_Index1601[] = 
{
	{"RPDO2 Mapping", 0x160100FF, OD_OBJCODE_RECORD, OD_DATATYPE_PDOMAP, OD_ACCESS_RW, (void *)&Receive_PDO_2_Mapping, 9, NULL, "RPDO2映射参数" },
};
OD_OI_TypeDef  Receive_PDO_2_Mapping[]=
{
	{"RPDO2 MappingCount", 0x16010000, OD_OBJCODE_NULL, OD_DATATYPE_U8,  OD_ACCESS_RW,  (void *)&TestSlave_highestSubIndex_obj1601, 0, NULL, "最高子索引数" },	
	{"RPDO2 Mapping1",  	    0x16010001, OD_OBJCODE_NULL, OD_DATATYPE_U32, OD_ACCESS_RW,  (void *)&TestSlave_obj1601[0], 0, NULL, "映射参数值为 200A0001" },
	{"RPDO2 Mapping2",  	    0x16010002, OD_OBJCODE_NULL, OD_DATATYPE_U32, OD_ACCESS_RW,  (void *)&TestSlave_obj1601[1], 0, NULL, "映射参数值为 200A0001" },
	{"RPDO2 Mapping3",  	    0x16010003, OD_OBJCODE_NULL, OD_DATATYPE_U32, OD_ACCESS_RW,  (void *)&TestSlave_obj1601[2], 0, NULL, "映射参数值为 200A0001" },
	{"RPDO2 Mapping4",  	    0x16010004, OD_OBJCODE_NULL, OD_DATATYPE_U32, OD_ACCESS_RW,  (void *)&TestSlave_obj1601[3], 0, NULL, "映射参数值为 200A0001" },
	{"RPDO2 Mapping5",  	    0x16010005, OD_OBJCODE_NULL, OD_DATATYPE_U32, OD_ACCESS_RW,  (void *)&TestSlave_obj1601[4], 0, NULL, "映射参数值为 200A0001" },
	{"RPDO2 Mapping6",  	    0x16010006, OD_OBJCODE_NULL, OD_DATATYPE_U32, OD_ACCESS_RW,  (void *)&TestSlave_obj1601[5], 0, NULL, "映射参数值为 200A0001" },
	{"RPDO2 Mapping7",  	    0x16010007, OD_OBJCODE_NULL, OD_DATATYPE_U32, OD_ACCESS_RW,  (void *)&TestSlave_obj1601[6], 0, NULL, "映射参数值为 200A0001" },
	{"RPDO2 Mapping8",  	    0x16010008, OD_OBJCODE_NULL, OD_DATATYPE_U32, OD_ACCESS_RW,  (void *)&TestSlave_obj1601[7], 0, NULL, "映射参数值为 200A0001" },
};

///////////////////////////////////////////////////////////////////////////

extern OD_OI_TypeDef  Receive_PDO_3_Mapping[];
UNS8 TestSlave_highestSubIndex_obj1602 = 4; /* number of subindex - 1*/
UNS32 TestSlave_obj1602[] = 
                    {
                      0,	
					  0,
					  0,
					  0,
                    };
OD_OI_TypeDef TestSlave_Index1602[] = 
{
	{"RPDO3 Mapping", 0x160200FF, OD_OBJCODE_RECORD, OD_DATATYPE_PDOMAP, OD_ACCESS_RW, (void *)&Receive_PDO_3_Mapping, 5, NULL, "RPDO3映射参数" },
};
OD_OI_TypeDef  Receive_PDO_3_Mapping[]=
{
  {"RPDO3 MappingCount", 0x16020000, OD_OBJCODE_NULL, OD_DATATYPE_U8,  OD_ACCESS_RW,  (void *)&TestSlave_highestSubIndex_obj1602, 0, NULL, "最高子索引数" },	
  {"RPDO3 Mapping1",  	    0x16020001, OD_OBJCODE_NULL, OD_DATATYPE_U32, OD_ACCESS_RW,  (void *)&TestSlave_obj1602[0], 0, NULL, "" },
  {"RPDO3 Mapping2",  	    0x16020002, OD_OBJCODE_NULL, OD_DATATYPE_U32, OD_ACCESS_RW,  (void *)&TestSlave_obj1602[1], 0, NULL, "" },
  {"RPDO3 Mapping3",  	    0x16020003, OD_OBJCODE_NULL, OD_DATATYPE_U32, OD_ACCESS_RW,  (void *)&TestSlave_obj1602[2], 0, NULL, "" },  
  {"RPDO3 Mapping4",  	    0x16020004, OD_OBJCODE_NULL, OD_DATATYPE_U32, OD_ACCESS_RW,  (void *)&TestSlave_obj1602[3], 0, NULL, "" },    
};

///////////////////////////////////////////////////////////////////////////

extern OD_OI_TypeDef  Receive_PDO_4_Mapping[];
UNS8 TestSlave_highestSubIndex_obj1603 = 0; /* number of subindex - 1*/
UNS32 TestSlave_obj1603[] = 
                    {
                      0x200C0010	
                    };
OD_OI_TypeDef TestSlave_Index1603[] = 
{
	{"RPDO4 Mapping", 0x160300FF, OD_OBJCODE_RECORD, OD_DATATYPE_PDOMAP, OD_ACCESS_RW, (void *)&Receive_PDO_4_Mapping, 2, NULL, "SDO服务器参数" },
};
OD_OI_TypeDef  Receive_PDO_4_Mapping[]=
{
  {"RPDO4 MappingCount", 0x16030000, OD_OBJCODE_NULL, OD_DATATYPE_U8,  OD_ACCESS_RW,  (void *)&TestSlave_highestSubIndex_obj1603, 0, NULL, "最高子索引数" },	
  {"RPDO4 Mapping1",  	 0x16030001, OD_OBJCODE_NULL, OD_DATATYPE_U32, OD_ACCESS_RW,  (void *)&TestSlave_obj1603[0], 0, NULL, "映射参数值为 200C0010" },
};

///////////////////////////////////////////////////////////////////////////

extern OD_OI_TypeDef  Receive_PDO_5_Mapping[];
UNS8 TestSlave_highestSubIndex_obj1604 = 0; /* number of subindex - 1*/
UNS32 TestSlave_obj1604[] = 
                    {
                      0x200C0010	
                    };
OD_OI_TypeDef TestSlave_Index1604[] = 
{
	{"RPDO5 Mapping", 0x160400FF, OD_OBJCODE_RECORD, OD_DATATYPE_PDOMAP, OD_ACCESS_RW, (void *)&Receive_PDO_5_Mapping, 2, NULL, "SDO服务器参数" },
};
OD_OI_TypeDef  Receive_PDO_5_Mapping[]=
{
  {"RPDO5 MappingCount", 0x16040000, OD_OBJCODE_NULL, OD_DATATYPE_U8,  OD_ACCESS_RW,  (void *)&TestSlave_highestSubIndex_obj1604, 0, NULL, "最高子索引数" },	
  {"RPDO5 Mapping1",  	 0x16040001, OD_OBJCODE_NULL, OD_DATATYPE_U32, OD_ACCESS_RW,  (void *)&TestSlave_obj1604[0], 0, NULL, "映射参数值为 200C0010" },
};
/*******************************************************************************************************************************************/
/*******************************************************************************************************************************************/

extern OD_OI_TypeDef  Transmit_PDO_1_Parameter[];
UNS8 TestSlave_highestSubIndex_obj1800 = 5; /* number of subindex - 1*/
UNS32 TestSlave_obj1800[] = 
                    {
                      0x180,	/* 0x18000001 */
                      0x0,	/* 0x18000002 */
					  0x0,	/* 0x18000003 */
                      0x0,	/* 0x18000004 */
                      0x0,	/* 0x18000005 */
                    };
ODCallback_t TestSlave_Index1800_callbacks[] = 
 {
   NULL,
   NULL,
   NULL,
   NULL,
   NULL,
   NULL,
 };
OD_OI_TypeDef TestSlave_Index1800[] = 
{
	{"TPDO1 Com", 0x180000FF, OD_OBJCODE_RECORD, OD_DATATYPE_PDOCP, OD_ACCESS_RW, (void *)&Transmit_PDO_1_Parameter, 6, NULL, "SDO服务器参数" },
};
OD_OI_TypeDef  Transmit_PDO_1_Parameter[]=
{
  {"TPDO1 SubCount", 0x18000000, OD_OBJCODE_NULL, OD_DATATYPE_U8,  OD_ACCESS_C,   (void *)&TestSlave_highestSubIndex_obj1800, 0, NULL, "最高子索引数" },	
  {"TPDO1 COB_ID_used_by_PDO",  		 0x18000001, OD_OBJCODE_NULL, OD_DATATYPE_U32, OD_ACCESS_RW,  (void *)&TestSlave_obj1800[0], 0, NULL, "TPDO使用的COB_ID" },
  {"TPDO1 Transmission_Type", 		     0x18000002, OD_OBJCODE_NULL, OD_DATATYPE_U8,  OD_ACCESS_RW,  (void *)&TestSlave_obj1800[1], 0, NULL, "传输类型" },
  {"TPDO1 Inhibit_Time",  			     0x18000003, OD_OBJCODE_NULL, OD_DATATYPE_U32, OD_ACCESS_RW,  (void *)&TestSlave_obj1800[2], 0, NULL, "抑制时间，单位为100us" },
  {"TPDO1 Compatibility_Entry",		     0x18000004, OD_OBJCODE_NULL, OD_DATATYPE_U8,  OD_ACCESS_RW,  (void *)&TestSlave_obj1800[3], 0, NULL, "保留" },
  {"TPDO1 Event_Timer", 				 0x18000005, OD_OBJCODE_NULL, OD_DATATYPE_U32, OD_ACCESS_RW,  (void *)&TestSlave_obj1800[4], 0, NULL, "事件定时器,单位为ms" }
};

///////////////////////////////////////////////////////////////////////////

extern OD_OI_TypeDef  Transmit_PDO_1_Mapping[];
//extern int pvt_o_pos_ref;
UNS8 TestSlave_highestSubIndex_obj1A00 = 2; /* number of subindex - 1*/
UNS32 TestSlave_obj1A00[] = 
                    {
                      0,	/* TestSlave_obj1A00[0] */
                      0,	/* TestSlave_obj1A00[1] */
//                      0,	/* TestSlave_obj1A00[2] */
//                      0,	/* TestSlave_obj1A00[3] */
//                      0,	/* TestSlave_obj1A00[4] */
//                      0,	/* TestSlave_obj1A00[5] */
//                      0,	/* TestSlave_obj1A00[6] */
//                      0,	/* TestSlave_obj1A00[7] */
                    };
OD_OI_TypeDef TestSlave_Index1A00[] = 
{
	{"TPDO1 Mapping", 0x1A0000FF, OD_OBJCODE_RECORD, OD_DATATYPE_PDOMAP, OD_ACCESS_RW, (void *)&Transmit_PDO_1_Mapping, 3, NULL, "TPDO1映射参数" },
};
OD_OI_TypeDef  Transmit_PDO_1_Mapping[]=
{
	{"TPDO1 MappingCount", 0x1A000000, OD_OBJCODE_NULL, OD_DATATYPE_U8,  OD_ACCESS_RW,  (void *)&TestSlave_highestSubIndex_obj1A00, 0, NULL, "最高子索引数" },	
	{"TPDO1 Mapping1",     0x1A000001, OD_OBJCODE_NULL, OD_DATATYPE_U32, OD_ACCESS_RW,  (void *)&TestSlave_obj1A00[0], 0, NULL, "映射参数值为20000001" },									
	{"TPDO1 Mapping2", 	   0x1A000002, OD_OBJCODE_NULL, OD_DATATYPE_U32, OD_ACCESS_RW,  (void *)&TestSlave_obj1A00[1], 0, NULL, "映射参数值为20010001" },					//pvt_o_vel_ref
//	{"TPDO1 Mapping3",     0x1A000003, OD_OBJCODE_NULL, OD_DATATYPE_U32, OD_ACCESS_RW,  (void *)&TestSlave_obj1A00[2], 0, NULL, "映射参数值为20020001" },
//	{"TPDO1 Mapping4",	   0x1A000004, OD_OBJCODE_NULL, OD_DATATYPE_U32, OD_ACCESS_RW,  (void *)&TestSlave_obj1A00[3], 0, NULL, "映射参数值为20030001" },
//	{"TPDO1 Mapping5", 	   0x1A000005, OD_OBJCODE_NULL, OD_DATATYPE_U32, OD_ACCESS_RW,  (void *)&TestSlave_obj1A00[4], 0, NULL, "映射参数值为20040001" },
//	{"TPDO1 Mapping6",     0x1A000006, OD_OBJCODE_NULL, OD_DATATYPE_U32, OD_ACCESS_RW,  (void *)&TestSlave_obj1A00[5], 0, NULL, "映射参数值为20050001" },
//	{"TPDO1 Mapping7", 	   0x1A000007, OD_OBJCODE_NULL, OD_DATATYPE_U32, OD_ACCESS_RW,  (void *)&TestSlave_obj1A00[6], 0, NULL, "映射参数值为20060001" },
//	{"TPDO1 Mapping8",     0x1A000008, OD_OBJCODE_NULL, OD_DATATYPE_U32, OD_ACCESS_RW,  (void *)&TestSlave_obj1A00[7], 0, NULL, "映射参数值为20070001" },
};

///////////////////////////////////////////////////////////////////////////

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/**************************************************************************************************************************************/
/**************************************************************************************************************************************/
/*******************************************************************************************************************************************/
/*******************************************************************************************************************************************/
/*******************************************************************************************************************************************/


extern OD_OI_TypeDef  TestSlave_Obj2000[];
UNS32 RPDO1DATA1;
UNS32 RPDO1DATA2;
OD_OI_TypeDef TestSlave_Index2000[] = 
{
	{"Mapped variable RPDO1", 0x200000FF, OD_OBJCODE_RECORD, OD_DATATYPE_PDOMAP, OD_ACCESS_RW, (void *)&TestSlave_Obj2000, 2, NULL, "SDO服务器参数" },
};
OD_OI_TypeDef TestSlave_Obj2000[] = 
{
	{"Mapped variable RPDO1DATA1", 0x20000001, OD_OBJCODE_VAR, OD_DATATYPE_U32, OD_ACCESS_RW, (void *)&RPDO1DATA1, 0, NULL, "Mapped variable SlaveMap1" },
	{"Mapped variable RPDO1DATA2", 0x20000002, OD_OBJCODE_VAR, OD_DATATYPE_U32, OD_ACCESS_RW, (void *)&RPDO1DATA2, 0, NULL, "Mapped variable SlaveMap2" },
};

///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////

extern OD_OI_TypeDef  TestSlave_Obj2002[];
UNS32 TPDO1DATA1=0x01234567;
UNS32 TPDO1DATA2=0x89ABCDEF;
OD_OI_TypeDef TestSlave_Index2002[] = 
{
	{"Mapped variable TPDO1", 0x200200FF, OD_OBJCODE_RECORD, OD_DATATYPE_PDOMAP, OD_ACCESS_RW, (void *)&TestSlave_Obj2002, 2, NULL, "SDO服务器参数" },
};
OD_OI_TypeDef TestSlave_Obj2002[] = 
{
	{"Mapped variable TPDO1DATA1", 0x20020001, OD_OBJCODE_VAR, OD_DATATYPE_U32, OD_ACCESS_RW, (void *)&TPDO1DATA1, 0, NULL, "Mapped variable SlaveMap1" },
	{"Mapped variable TPDO1DATA2", 0x20020002, OD_OBJCODE_VAR, OD_DATATYPE_U32, OD_ACCESS_RW, (void *)&TPDO1DATA2, 0, NULL, "Mapped variable SlaveMap2" },
};

///////////////////////////////////////////////////////////////////////////


///////////////////////////////////////////////////////////////////////////
extern OD_OI_TypeDef  TestSlave_Obj2003[];
UNS32 TPDO2DATA1=0x01;
UNS32 TPDO2DATA2=0x02;
UNS32 TPDO2DATA3=0x03;
UNS32 TPDO2DATA4=0x04;
UNS32 TPDO2DATA5=0x05;
UNS32 TPDO2DATA6=0x06;
UNS32 TPDO2DATA7=0x07;
UNS32 TPDO2DATA8=0x08;
OD_OI_TypeDef TestSlave_Index2003[] = 
{
	{"Mapped variable TPDO2", 0x200300FF, OD_OBJCODE_RECORD, OD_DATATYPE_PDOMAP, OD_ACCESS_RW, (void *)&TestSlave_Obj2003, 8, NULL, "SDO服务器参数" },
};

OD_OI_TypeDef TestSlave_Obj2003[] = 
{
	{"Mapped variable TPDO2DATA1", 0x20030001, OD_OBJCODE_VAR, OD_DATATYPE_U8, OD_ACCESS_RW, (void *)&TPDO2DATA1, 0, NULL, "Mapped variable SlaveMap3" },
	{"Mapped variable TPDO2DATA2", 0x20030002, OD_OBJCODE_VAR, OD_DATATYPE_U8, OD_ACCESS_RW, (void *)&TPDO2DATA2, 0, NULL, "Mapped variable SlaveMap4" },
	{"Mapped variable TPDO2DATA3", 0x20030003, OD_OBJCODE_VAR, OD_DATATYPE_U8, OD_ACCESS_RW, (void *)&TPDO2DATA3, 0, NULL, "Mapped variable SlaveMap5" },
	{"Mapped variable TPDO2DATA4", 0x20030004, OD_OBJCODE_VAR, OD_DATATYPE_U8, OD_ACCESS_RW, (void *)&TPDO2DATA4, 0, NULL, "Mapped variable SlaveMap6" },
	{"Mapped variable TPDO2DATA5", 0x20030005, OD_OBJCODE_VAR, OD_DATATYPE_U8, OD_ACCESS_RW, (void *)&TPDO2DATA5, 0, NULL, "Mapped variable SlaveMap7" },
	{"Mapped variable TPDO2DATA6", 0x20030006, OD_OBJCODE_VAR, OD_DATATYPE_U8, OD_ACCESS_RW, (void *)&TPDO2DATA6, 0, NULL, "Mapped variable SlaveMap8" },
	{"Mapped variable TPDO2DATA7", 0x20030007, OD_OBJCODE_VAR, OD_DATATYPE_U8, OD_ACCESS_RW, (void *)&TPDO2DATA7, 0, NULL, "Mapped variable SlaveMap9" },
	{"Mapped variable TPDO2DATA8", 0x20030008, OD_OBJCODE_VAR, OD_DATATYPE_U8, OD_ACCESS_RW, (void *)&TPDO2DATA8, 0, NULL, "Mapped variable SlaveMap10" },
	
};


Time timetest1={9,8,7,6,5,5,3,2,1};
int Timelength=sizeof(Time);
OD_OI_TypeDef TestSlave_Index2004[] = 
{
	{"Mapped variable SDO1", 0x20040000, OD_OBJCODE_VAR, TIME, OD_ACCESS_RW, (void *)&timetest1, 0, NULL, "SDO服务器参数" },
};



Time timetest2={1,2,3,4,5,6,7,8,9};
OD_OI_TypeDef TestSlave_Index2005[] = 
{
	{"Mapped variable SDO1", 0x20050000, OD_OBJCODE_VAR, TIME, OD_ACCESS_RW, (void *)&timetest2, 0, NULL, "SDO服务器参数" },
};


Cost cost1 ={5,8,3,4,5,6,7,8,9,10,11,12,18};
int Costlength=sizeof(Cost);
OD_OI_TypeDef TestSlave_Index2006[] = 
{
	{"Mapped variable SDO1", 0x20060000, OD_OBJCODE_VAR, COST, OD_ACCESS_RW, (void *)&cost1, 0, NULL, "SDO服务器参数" },
};

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/** new OD data
*/

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////姿态角数据pitch roll yaw
extern OD_OI_TypeDef IMU_Data[];
int32_t EULER[3];
OD_OI_TypeDef Number_IMU_Data[] =
{
    {"IMU data",        0x2F0400FF, OD_OBJCODE_ARRAY,  OD_DATATYPE_I32,    OD_ACCESS_RW,  (void *)&IMU_Data, 3, NULL, "pitch roll yaw"},	
};

OD_OI_TypeDef IMU_Data[] = 
{ 
    {"pitch state",     0x2F040001, OD_OBJCODE_VAR, OD_DATATYPE_I32, OD_ACCESS_RW, (void *)&EULER[0], 0, NULL, "俯仰角" },
    {"roll state",      0x2F040002, OD_OBJCODE_VAR, OD_DATATYPE_I32, OD_ACCESS_RW, (void *)&EULER[1], 0, NULL, "翻滚角" },
    {"yaw state",       0x2F040003, OD_OBJCODE_VAR, OD_DATATYPE_I32, OD_ACCESS_RW, (void *)&EULER[2], 0, NULL, "偏航角" },

};

OD_OI_TypeDef  TestSlave_objdict[]=
{
	{"Device Type", 						0x10000000, OD_OBJCODE_VAR, 	OD_DATATYPE_U32, 	OD_ACCESS_R, 	(void *)&TestSlave_obj1000, 				0, NULL, "16位的设备协议或应用协议 + 16位的逻辑设备的附加功能信息" },
	{"Error Register", 						0x10010000, OD_OBJCODE_VAR, 	OD_DATATYPE_U8, 	OD_ACCESS_R, 	(void *)&TestSlave_obj1001, 				0, NULL, "Canopen设备内部错误信息记录" },
	{"Pre-defined Error Field", 			0x100300FF, OD_OBJCODE_ARRAY, 	OD_DATATYPE_U32, 	OD_ACCESS_RW, 	(void *)&Error_Field, 						9, NULL, "Canopen设备内部错误信息记录" },
	{"SYNC COB ID", 						0x10050000, OD_OBJCODE_VAR, 	OD_DATATYPE_U32, 	OD_ACCESS_RW, 	(void *)&TestSlave_obj1005, 				0, NULL, "已配置的同步对象的COB-ID" },
	{"Communication Cycle Period", 			0x10060000, OD_OBJCODE_VAR, 	OD_DATATYPE_U32, 	OD_ACCESS_RW, 	(void *)&TestSlave_obj1006, 				0, NULL, "SYNC时间间隔，单位是us" },
	{"GuardTime", 							0x100C0000, OD_OBJCODE_VAR, 	OD_DATATYPE_U16, 	OD_ACCESS_RW, 	(void *)&TestSlave_obj100C, 				0, NULL, "监护周期，单位为ms" },
	{"LifeTimeFactor", 						0x100D0000, OD_OBJCODE_VAR, 	OD_DATATYPE_U8, 	OD_ACCESS_RW, 	(void *)&TestSlave_obj100D, 				0, NULL, "生存周期因子" },
	{"Store parameters", 					0x101000FF, OD_OBJCODE_ARRAY, 	OD_DATATYPE_U32, 	OD_ACCESS_RW, 	(void *)&Store_parameters, 					6, NULL, "此对象控制保存参数到非易失性存储器中" },
	{"Restore Default Parameters", 			0x101100FF, OD_OBJCODE_ARRAY, 	OD_DATATYPE_U32, 	OD_ACCESS_RW, 	(void *)&Restore_Default_Parameters, 		6, NULL, "此对象控制保存参数到非易失性存储器中" },
	{"Emergency COB ID", 					0x10140000, OD_OBJCODE_VAR, 	OD_DATATYPE_U32, 	OD_ACCESS_RW, 	(void *)&TestSlave_obj1014, 				0, NULL, "应急消息 COB_ID" },
	{"Consumer Heartbeat Time", 			0x101600FF, OD_OBJCODE_ARRAY, 	OD_DATATYPE_U32, 	OD_ACCESS_RW, 	(void *)&Consumer_Heartbeat_Time, 			5, NULL, "消费者心跳超时" },
	{"Producer Heartbeat Time", 			0x10170000, OD_OBJCODE_VAR, 	OD_DATATYPE_U16, 	OD_ACCESS_RW, 	(void *)&TestSlave_obj1017, 				0, NULL, "生产者心跳超时" },
	{"Identity", 							0x101800FF, OD_OBJCODE_RECORD, 	OD_DATATYPE_ID, 	OD_ACCESS_R, 	(void *)&Identity, 							5, NULL, "消费者心跳超时" },
	{"SSDO Par", 							0x120000FF, OD_OBJCODE_RECORD, 	OD_DATATYPE_SDOP, 	OD_ACCESS_R, 	(void *)&Server_SDO_Parameter, 				4, NULL, "SDO服务器参数" },
	{"CSDO Par", 							0x128000FF, OD_OBJCODE_RECORD, 	OD_DATATYPE_SDOP, 	OD_ACCESS_R, 	(void *)&Client_SDO_Parameter, 				4, NULL, "SDO服务器参数" },
	{"RPDO1 Com", 							0x140000FF, OD_OBJCODE_RECORD, 	OD_DATATYPE_PDOCP, 	OD_ACCESS_RW, 	(void *)&Receive_PDO_1_Parameter, 			6, NULL, "SDO服务器参数" },
	{"RPDO2 Com", 							0x140100FF, OD_OBJCODE_RECORD, 	OD_DATATYPE_PDOCP, 	OD_ACCESS_RW, 	(void *)&Receive_PDO_2_Parameter, 			6, NULL, "SDO服务器参数" },
	{"RPDO3 Com", 							0x140200FF, OD_OBJCODE_RECORD,    OD_DATATYPE_PDOCP,  OD_ACCESS_RW, 	(void *)&Receive_PDO_3_Parameter, 			6, NULL, "SDO服务器参数" },
	{"RPDO4 Com", 							0x140301FF, OD_OBJCODE_RECORD,    OD_DATATYPE_PDOCP,  OD_ACCESS_RW, 	(void *)&Receive_PDO_4_Parameter, 			6, NULL, "SDO服务器参数" },
	{"RPDO5 Com", 							0x140401FF, OD_OBJCODE_RECORD,    OD_DATATYPE_PDOCP,  OD_ACCESS_RW, 	(void *)&Receive_PDO_5_Parameter, 			6, NULL, "SDO服务器参数" },
	{"RPDO1 Mapping", 						0x160000FF, OD_OBJCODE_RECORD, 	OD_DATATYPE_PDOMAP, OD_ACCESS_RW, 	(void *)&Receive_PDO_1_Mapping, 			5, NULL, "TPDO1映射参数" },
	{"RPDO2 Mapping", 						0x160100FF, OD_OBJCODE_RECORD, 	OD_DATATYPE_PDOMAP, OD_ACCESS_RW, 	(void *)&Receive_PDO_2_Mapping, 			9, NULL, "SDO服务器参数" },
	{"RPDO3 Mapping", 						0x160200FF, OD_OBJCODE_RECORD,    OD_DATATYPE_PDOMAP, 	OD_ACCESS_RW, 	(void *)&Receive_PDO_3_Mapping, 			5, NULL, "SDO服务器参数" },
	{"RPDO4 Mapping", 						0x160300FF, OD_OBJCODE_RECORD,  OD_DATATYPE_PDOMAP, 	OD_ACCESS_RW, 	(void *)&Receive_PDO_4_Mapping, 			2, NULL, "SDO服务器参数" },
	{"RPDO5 Mapping", 						0x160400FF, OD_OBJCODE_RECORD,  OD_DATATYPE_PDOMAP, 	OD_ACCESS_RW, 	(void *)&Receive_PDO_5_Mapping, 			2, NULL, "SDO服务器参数" },
	{"TPDO1 Com", 							0x180000FF, OD_OBJCODE_RECORD, 	OD_DATATYPE_PDOCP, 	OD_ACCESS_RW, 	(void *)&Transmit_PDO_1_Parameter, 			6, NULL, "SDO服务器参数" },
	{"TPDO1 Mapping", 						0x1A0000FF, OD_OBJCODE_RECORD, 	OD_DATATYPE_PDOMAP, OD_ACCESS_RW, 	(void *)&Transmit_PDO_1_Mapping, 			3, NULL, "TPDO1映射参数" },
	{"Mapped variable RPDO1", 				0x200000FF, OD_OBJCODE_RECORD, 	OD_DATATYPE_PDOMAP, OD_ACCESS_RW, 	(void *)&TestSlave_Obj2000, 				2, NULL, "SDO服务器参数" },
	{"Mapped variable TPDO1", 				0x200200FF, OD_OBJCODE_RECORD, 	OD_DATATYPE_PDOMAP, OD_ACCESS_RW, 	(void *)&TestSlave_Obj2002, 				2, NULL, "SDO服务器参数" },
	{"Mapped variable TPDO2", 				0x200300FF, OD_OBJCODE_RECORD, 	OD_DATATYPE_PDOMAP, OD_ACCESS_RW, 	(void *)&TestSlave_Obj2003, 				8, NULL, "SDO服务器参数" },
	{"Mapped variable SDO1", 				0x20040000, OD_OBJCODE_VAR, 	TIME, 				OD_ACCESS_RW, 	(void *)&timetest1, 						0, NULL, "SDO服务器参数" },
	{"Mapped variable SDO1", 				0x20050000, OD_OBJCODE_VAR, 	TIME, 				OD_ACCESS_RW, 	(void *)&timetest2, 						0, NULL, "SDO服务器参数" },
	{"Mapped variable SDO1", 				0x20060000, OD_OBJCODE_VAR, 	COST, 				OD_ACCESS_RW, 	(void *)&cost1, 							0, NULL, "SDO服务器参数" },

	{"IMU data",            0x2F0400FF, OD_OBJCODE_ARRAY,  OD_DATATYPE_I32,    OD_ACCESS_RW,  (void *)&IMU_Data,             3, NULL, "pitch roll yaw"},	
};


/* 
 * To count at which received SYNC a PDO must be sent.
 * Even if no pdoTransmit are defined, at least one entry is computed
 * for compilations issues.
 */


// data definition , data will be initialized when compiling 
//int objnum = sizeof(TestSlave_objdict)/sizeof(TestSlave_objdict[0]);

s_PDO_status TestSlave_PDO_status[5] = {s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer};

UNS16 TestSlave_ObjdictSize = sizeof(TestSlave_objdict)/sizeof(TestSlave_objdict[0]);

// TestSlave_ObjdictSize will give it value to TestSlave_Data.ObjdictSize after the macro expanding
// others variable will be initialized like TestSlave_Data.ObjdictSize also
CO_Data TestSlave_Data = CANOPEN_NODE_DATA_INITIALIZER( TestSlave, CAN_NUM1, CAN_PORT1, TIM2);

